#!/usr/bin/env bash
# Hard-build rollout-shield into a user-local prefix at ~/usr/.
#
# Layout produced:
#
#   ~/usr/
#   ├── bin/
#   │   ├── rollout-shield            # main CLI
#   │   └── rollout-shield-daemon     # long-lived monitor launcher
#   ├── lib/
#   │   └── python/
#   │       └── rollout_shield/       # the Python package (copy, not symlink)
#   ├── share/
#   │   └── rollout-shield/
#   │       └── interface/            # HTML/JS/CSS dashboard assets
#   ├── etc/
#   │   └── rollout-shield/
#   │       ├── config.example.json   # default config template
#   │       └── rollout-shield.service # systemd --user unit
#   └── INSTALLED_AT                  # ISO timestamp of this install
#
# Idempotent: re-running overwrites a clean copy from the repo source.
# State stays at ~/.rollout-shield/ — install never touches runtime state.
#
# Usage:
#   scripts/install.sh                # install into ~/usr/
#   scripts/install.sh --prefix /tmp/x # override prefix (test only)
#   scripts/install.sh --no-path      # skip PATH hint
#
# Exit codes:
#   0 — installed cleanly
#   1 — install failed (see stderr)

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PREFIX="${HOME}/usr"
WRITE_PATH_HINT=1

while [[ $# -gt 0 ]]; do
  case "$1" in
    --prefix)  PREFIX="$2"; shift 2 ;;
    --no-path) WRITE_PATH_HINT=0; shift ;;
    -h|--help)
      sed -n '2,28p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//'
      exit 0
      ;;
    *) echo "unknown arg: $1" >&2; exit 1 ;;
  esac
done

log() { printf '[install] %s\n' "$*" >&2; }
fail() { printf '[install] FAIL: %s\n' "$*" >&2; exit 1; }

[[ -d "$REPO_ROOT/rollout_shield" ]] || fail "rollout_shield/ not found at $REPO_ROOT"
[[ -d "$REPO_ROOT/rollout_shield/interface" ]] || fail "interface assets missing"

mkdir -p "$PREFIX/bin"
mkdir -p "$PREFIX/lib/python"
mkdir -p "$PREFIX/share/rollout-shield"
mkdir -p "$PREFIX/etc/rollout-shield"

log "prefix: $PREFIX"

# --- 1. Copy the Python package (real copy, not symlink) ---
log "copying rollout_shield/ → $PREFIX/lib/python/rollout_shield/"
rm -rf "$PREFIX/lib/python/rollout_shield"
cp -a "$REPO_ROOT/rollout_shield" "$PREFIX/lib/python/rollout_shield"
# strip pyc caches
find "$PREFIX/lib/python/rollout_shield" -type d -name __pycache__ -exec rm -rf {} + 2>/dev/null || true

# --- 2. Copy the interface assets ---
log "copying interface/ → $PREFIX/share/rollout-shield/interface/"
rm -rf "$PREFIX/share/rollout-shield/interface"
cp -a "$REPO_ROOT/rollout_shield/interface" "$PREFIX/share/rollout-shield/interface"

# --- 3. Copy the CLI entry scripts (rewritten shims) ---
log "writing CLI shims → $PREFIX/bin/"

write_cli_shim() {
  local name="$1" target_module="$2"
  cat > "$PREFIX/bin/$name" <<EOF
#!/usr/bin/env python3
# Auto-generated by scripts/install.sh — hard build shim.
# Targets the rollout_shield package installed at:
#   $PREFIX/lib/python/rollout_shield/
# Do not edit by hand — re-run scripts/install.sh to regenerate.

import os
import sys
from pathlib import Path

_PREFIX = Path("$PREFIX").expanduser()
_PKG_PARENT = _PREFIX / "lib" / "python"
_REPO_PKG_PARENT = Path("$REPO_ROOT").expanduser()

# Search order:
#   1. ~/usr/lib/python  (this install)
#   2. <repo>/rollout_shield  (dev fallback when running from the repo)
for parent in (_PKG_PARENT, _REPO_PKG_PARENT):
    pstr = str(parent)
    if pstr not in sys.path and (parent / "rollout_shield").is_dir():
        sys.path.insert(0, pstr)

try:
    from rollout_shield.$target_module import main
except ImportError as exc:
    sys.stderr.write(
        f"$name: failed to import rollout_shield.$target_module ({exc}).\\n"
        f"  searched: {_PKG_PARENT}, {_REPO_PKG_PARENT}\\n"
        f"  reinstall with: scripts/install.sh\\n"
    )
    raise

if __name__ == "__main__":
    sys.exit(main())
EOF
  chmod 0755 "$PREFIX/bin/$name"
}

write_cli_shim rollout-shield cli
write_cli_shim rollout-shield-monitor monitor_daemon

# backward-compatible alias the existing systemd / launchd units reference
ln -sf rollout-shield "$PREFIX/bin/rollout-shield-daemon" 2>/dev/null || true

# --- 4. Install default config + systemd --user unit ---
log "writing default config + systemd unit → $PREFIX/etc/rollout-shield/"

cat > "$PREFIX/etc/rollout-shield/config.example.json" <<'EOF'
{
  "schema_version": 1,
  "monitor_interval_seconds": 60,
  "alert_webhook_url": "",
  "claim_retention_days": 2555,
  "health_window_seconds": 300,
  "reputation_decay_days": 30,
  "self_heal_enabled": true,
  "self_heal_interval_cycles": 5
}
EOF

cat > "$PREFIX/etc/rollout-shield/rollout-shield.service" <<'EOF'
[Unit]
Description=rollout-shield persistent monitor
After=network-online.target

[Service]
Type=simple
ExecStart=%h/usr/bin/rollout-shield-monitor --daemon --foreground --interval 60
Restart=on-failure
RestartSec=5s
StandardOutput=journal
StandardError=journal

[Install]
WantedBy=default.target
EOF

# --- 5. Stamp the install ---
date -u +%Y-%m-%dT%H:%M:%SZ > "$PREFIX/INSTALLED_AT"
echo "$REPO_ROOT" > "$PREFIX/REPO_SOURCE"

# --- 6. Verify the install is callable ---
log "verifying install…"
if ! "$PREFIX/bin/rollout-shield" --version >/dev/null 2>&1; then
  fail "post-install verification failed — $PREFIX/bin/rollout-shield --version did not exit 0"
fi

log "installed: $("$PREFIX/bin/rollout-shield" --version)"

# --- 7. PATH hint (opt-out via --no-path) ---
if [[ "$WRITE_PATH_HINT" -eq 1 ]]; then
  if [[ ":$PATH:" != *":$PREFIX/bin:"* ]]; then
    log "PATH: $PREFIX/bin is not on PATH"
    log "      add with:  echo 'export PATH=\"\$HOME/usr/bin:\$PATH\"' >> ~/.bashrc"
    log "      or one-shot (current shell): export PATH=\"$PREFIX/bin:\$PATH\""
  else
    log "PATH: $PREFIX/bin already on PATH"
  fi
fi

cat <<EOF

[install] OK — rollout-shield hard-built into $PREFIX
[install] verify with: scripts/verify-install.sh
[install] uninstall:  scripts/uninstall.sh
EOF
