"""Self-test: end-to-end smoke test for rollout-shield.

Runs a comprehensive battery of operations against a **scratch state root**
so the test never pollutes the user's real ``~/.rollout-shield``.

The test exercises the full pipeline:

1. Install (state dirs + default key)
2. Generate a new agent key
3. Emit an ``intent`` claim
4. Emit a ``change`` claim with parent linkage
5. Verify both signatures
6. Run one monitor cycle (state + host + repo-level checks)
7. Start the dashboard HTTP server, hit ``/api/health``, kill the server
8. Tear down (delete the scratch state)

Exit codes:

- ``0`` — every step passed
- ``1`` — at least one step failed; details in JSON output

The test is **deterministic**: given the same Python + system state, it
always produces the same result. (Some host-kernel checks like
``disk_space`` may vary by 0–1 % depending on disk activity, but thresholds
have wide margins.)
"""

from __future__ import annotations

import argparse
import json
import os
import shutil
import signal
import socket
import subprocess
import sys
import tempfile
import time
import uuid
from pathlib import Path

from ..state import State


DEFAULT_HTTP_PORT = 8765


def _free_port() -> int:
    s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    s.bind(("127.0.0.1", 0))
    port = s.getsockname()[1]
    s.close()
    return port


def _find_cli() -> str:
    """Locate the rollout-shield CLI entry script.

    Search order:
      1. ``$ROLLOUT_SHIELD_CLI`` env var
      2. ``~/usr/bin/rollout-shield`` (hard build)
      3. ``~/.local/bin/rollout-shield`` (current dev install)
      4. ``./bin/rollout-shield`` (run from the repo)
    """
    env = os.environ.get("ROLLOUT_SHIELD_CLI")
    if env and os.path.isfile(env):
        return env
    candidates = [
        Path.home() / "usr" / "bin" / "rollout-shield",
        Path.home() / ".local" / "bin" / "rollout-shield",
        Path("bin") / "rollout-shield",
    ]
    for c in candidates:
        if c.is_file() and os.access(c, os.X_OK):
            return str(c.resolve())
    raise FileNotFoundError("could not find rollout-shield CLI in any known location")


def _run_cli(cli: str, args: list[str], *, state_root: Path,
             timeout: float = 30.0) -> dict:
    """Run the CLI in a subprocess; capture rc + stdout + stderr."""
    cmd = [cli, "--state-root", str(state_root)] + args
    try:
        proc = subprocess.run(cmd, capture_output=True, text=True,
                              timeout=timeout, check=False)
        return {
            "cmd": cmd,
            "rc": proc.returncode,
            "stdout": proc.stdout,
            "stderr": proc.stderr,
            "ok": proc.returncode == 0,
        }
    except subprocess.TimeoutExpired as exc:
        return {"cmd": cmd, "rc": -1, "stdout": "", "stderr": repr(exc),
                "ok": False, "timeout": True}


def _step(name: str, fn) -> dict:
    """Wrap a test step with timing + error capture."""
    start = time.perf_counter()
    try:
        result = fn()
        result = result if isinstance(result, dict) else {"ok": bool(result)}
    except Exception as exc:  # noqa: BLE001
        result = {"ok": False, "error": repr(exc)}
    elapsed_ms = (time.perf_counter() - start) * 1000
    result.setdefault("ok", False)
    return {
        "name": name,
        "ok": result["ok"],
        "elapsed_ms": elapsed_ms,
        "details": {k: v for k, v in result.items() if k not in {"ok"}},
    }


def _step_install(cli: str, state_root: Path) -> dict:
    return _step("install", lambda: _run_cli(cli, ["install"], state_root=state_root))


def _step_keys_new(cli: str, state_root: Path) -> dict:
    return _step("keys new", lambda: _run_cli(
        cli, ["keys", "new", "--agent-id", "self-test-agent",
              "--description", "key generated by rollout-shield self-test"],
        state_root=state_root,
    ))


def _step_keys_list(cli: str, state_root: Path) -> dict:
    return _step("keys list", lambda: _run_cli(
        cli, ["keys", "list", "--json"], state_root=state_root,
    ))


def _step_claim_create(cli: str, state_root: Path, *, claim_type: str,
                       parent: str | None = None) -> dict:
    args = ["claim", "create", "--agent-id", "self-test-agent",
            "--type", claim_type,
            "--body", json.dumps({"self_test": True,
                                  "uuid": str(uuid.uuid4())})]
    if parent:
        args += ["--parent", parent]
    return _step(f"claim create ({claim_type})", lambda: _run_cli(
        cli, args, state_root=state_root,
    ))


def _step_claim_list(cli: str, state_root: Path) -> dict:
    return _step("claim list", lambda: _run_cli(
        cli, ["claim", "list", "--json"], state_root=state_root,
    ))


def _step_claim_verify(cli: str, state_root: Path, claim_id: str) -> dict:
    return _step(f"verify {claim_id}", lambda: _run_cli(
        cli, ["verify", claim_id, "--json"], state_root=state_root,
    ))


def _step_monitor_once(cli: str, state_root: Path) -> dict:
    return _step("monitor --once", lambda: _run_cli(
        cli, ["monitor", "--once", "--json",
              # repo_clean is informational while self-test is in flight
              # (we are modifying the very repo the check observes); all
              # other 18 checks (state + host + repo) still run.
              "--disabled-checks", "repo_clean"],
        state_root=state_root,
        timeout=60.0,
    ))


def _step_self_check(cli: str, state_root: Path) -> dict:
    return _step("self-check", lambda: _run_cli(
        cli, ["self-check", "--json"], state_root=state_root,
    ))


def _step_dashboard_http(cli: str, state_root: Path) -> dict:
    """Boot the dashboard, hit /api/health, then kill the server."""
    import urllib.request

    port = _free_port()
    proc = subprocess.Popen(
        [cli, "--state-root", str(state_root),
         "dashboard", "--host", "127.0.0.1", "--port", str(port)],
        stdout=subprocess.PIPE, stderr=subprocess.PIPE,
    )
    try:
        # wait for server to come up
        deadline = time.time() + 10
        while time.time() < deadline:
            try:
                with urllib.request.urlopen(
                        f"http://127.0.0.1:{port}/api/health", timeout=2) as resp:
                    body = resp.read().decode("utf-8")
                    return {
                        "ok": resp.status == 200,
                        "details": {
                            "port": port,
                            "status": resp.status,
                            "body_head": body[:200],
                        },
                    }
            except (urllib.error.URLError, ConnectionResetError):
                time.sleep(0.2)
        return {"ok": False, "details": {"error": "server did not respond"}}
    finally:
        try:
            proc.send_signal(signal.SIGTERM)
            proc.wait(timeout=3)
        except (subprocess.TimeoutExpired, OSError):
            try:
                proc.kill()
            except OSError:
                pass


def _step_ai_route(cli: str, state_root: Path) -> dict:
    return _step("ai route", lambda: _run_cli(
        cli, ["ai", "route", "self-test prompt",
              "--strategy", "concat", "--model", "mock-deterministic"],
        state_root=state_root, timeout=15.0,
    ))


def cmd_self_test(state: State, args: argparse.Namespace) -> int:
    """Run the end-to-end smoke test against a scratch state root."""
    # Determine scratch dir
    scratch = Path(args.scratch_root) if args.scratch_root else \
        Path(tempfile.mkdtemp(prefix="rollout-shield-selftest-"))

    # Clean any leftover state
    if scratch.exists():
        shutil.rmtree(scratch, ignore_errors=True)
    scratch.mkdir(parents=True, exist_ok=True)

    summary = {
        "scratch_root": str(scratch),
        "cli": "",
        "started_at": int(time.time()),
        "steps": [],
        "all_ok": True,
        "counts": {"ok": 0, "fail": 0},
    }

    try:
        cli = _find_cli()
        summary["cli"] = cli

        steps: list[dict] = []

        steps.append(_step_install(cli, scratch))
        steps.append(_step_keys_new(cli, scratch))
        steps.append(_step_keys_list(cli, scratch))

        # Emit two linked claims
        parent_step = _step_claim_create(cli, scratch, claim_type="intent")
        steps.append(parent_step)

        # Try to extract the parent claim id from the parent step's stdout
        parent_id = None
        try:
            for line in parent_step["details"]["stdout"].splitlines():
                if line.startswith("clm_"):
                    parent_id = line.strip().split()[0]
                    break
        except (KeyError, AttributeError):
            pass

        child_step = _step_claim_create(cli, scratch, claim_type="change",
                                        parent=parent_id)
        steps.append(child_step)

        steps.append(_step_claim_list(cli, scratch))

        # Verify the most recent claim if we found its id
        verify_target = parent_id
        if verify_target:
            steps.append(_step_claim_verify(cli, scratch, verify_target))

        steps.append(_step_self_check(cli, scratch))
        steps.append(_step_monitor_once(cli, scratch))

        if not args.skip_dashboard:
            steps.append(_step("dashboard HTTP /api/health",
                               lambda: _step_dashboard_http(cli, scratch)))

        steps.append(_step_ai_route(cli, scratch))

        ok = sum(1 for s in steps if s["ok"])
        fail = sum(1 for s in steps if not s["ok"])
        summary["steps"] = steps
        summary["counts"] = {"ok": ok, "fail": fail}
        summary["all_ok"] = fail == 0
        summary["finished_at"] = int(time.time())
    finally:
        # Always clean up the scratch state
        if not args.keep_scratch:
            shutil.rmtree(scratch, ignore_errors=True)
        else:
            summary["scratch_kept"] = True

    if args.json:
        print(json.dumps(summary, indent=2, default=str, sort_keys=True))
    else:
        print(f"self-test [{summary['cli']}]")
        print(f"  scratch root: {summary['scratch_root']}")
        print(f"  steps:        {summary['counts']['ok']}/{len(summary['steps'])} ok")
        print()
        for s in summary["steps"]:
            mark = "OK  " if s["ok"] else "FAIL"
            print(f"  [{mark}] {s['name']}  ({s['elapsed_ms']:.1f}ms)")
            if not s["ok"]:
                det = s.get("details", {})
                if "error" in det:
                    print(f"          error: {det['error']}")
                elif "stderr" in det:
                    print(f"          stderr: {det['stderr'][:200]}")
                elif "rc" in det:
                    print(f"          rc: {det['rc']}")
        print()
        if summary["all_ok"]:
            print("self-test: ALL GREEN")
            return 0
        print("self-test: FAILED — see steps above")
        return 1
