"""Model registry for rollout-shield.

Each model is a callable that takes a prompt and returns a dict::

    {
        "text":   str,       # the model output
        "tokens": int,       # approximate token count
        "meta":   dict,      # model-specific metadata
    }

The default registry ships with deterministic mock models — they
produce stable, reproducible outputs based on the prompt hash. This
lets the benchmark suite, leaderboard, and self-cycle engine operate
fully offline.

Real-model integrations (Anthropic, OpenAI, local llama.cpp, etc.) are
a drop-in: implement the same callable shape and register via
``register_model``.
"""

from __future__ import annotations

import hashlib
import time
from dataclasses import dataclass, field
from typing import Callable, Any


ModelFn = Callable[[str, dict], dict]


@dataclass
class ModelInfo:
    id: str
    name: str
    description: str
    family: str               # "mock" | "anthropic" | "openai" | ...
    fn: ModelFn
    cost_per_1k_tokens: float = 0.0
    meta: dict = field(default_factory=dict)

    def run(self, prompt: str, **kwargs) -> dict:
        return self.fn(prompt, kwargs)


# ---------- mock model implementations ----------


def _hash_digest(prompt: str, salt: str = "") -> str:
    h = hashlib.sha256()
    h.update(salt.encode("utf-8"))
    h.update(b"\x00")
    h.update(prompt.encode("utf-8"))
    return h.hexdigest()


def _approx_tokens(text: str) -> int:
    # rough approximation: ~4 chars per token
    return max(1, len(text) // 4)


def mock_deterministic(prompt: str, params: dict) -> dict:
    """A deterministic mock: output is a stable transformation of the prompt hash.

    Outputs a short structured response derived from the prompt. Useful
    for benchmarking where stability matters more than creativity.
    """
    digest = _hash_digest(prompt, "mock-deterministic")
    # 8 words picked by index from a fixed wordlist, plus the prompt head.
    wordlist = ("alpha bravo charlie delta echo foxtrot golf hotel "
                "india juliet kilo lima").split()
    seed = int(digest[:8], 16)
    words = [wordlist[(seed >> i) % len(wordlist)] for i in range(0, 32, 4)]
    body = " ".join(words)
    text = f"[deterministic:{digest[:12]}] {prompt[:80]}\n→ {body}"
    return {
        "text": text,
        "tokens": _approx_tokens(text),
        "meta": {"seed": seed, "digest": digest[:16]},
    }


def mock_creative(prompt: str, params: dict) -> dict:
    """A 'creative' mock: output varies more (uses timestamp salt).

    Same prompt produces different output across runs. Good for the
    benchmark diversity dimension.
    """
    salt = str(int(time.time()) // 300)  # 5-minute salt bucket
    digest = _hash_digest(prompt, f"creative:{salt}")
    wordlist = ("silver velvet quiet jade moon river amber saffron dusk dawn "
                "petal glacier").split()
    seed = int(digest[:8], 16)
    words = [wordlist[(seed >> i) % len(wordlist)] for i in range(0, 24, 3)]
    text = f"[creative:{digest[:12]}] {prompt[:80]}\n~ {' / '.join(words)} ~"
    return {
        "text": text,
        "tokens": _approx_tokens(text),
        "meta": {"seed": seed, "digest": digest[:16], "salt_bucket": salt},
    }


def mock_structured(prompt: str, params: dict) -> dict:
    """A 'structured' mock: output is JSON-shaped with stable keys.

    Useful for benchmarks that grade on JSON-schema conformance.
    """
    import json
    digest = _hash_digest(prompt, "structured")
    payload = {
        "kind": "structured-response",
        "digest": digest[:16],
        "prompt_head": prompt[:60],
        "tags": sorted({"a", "b", "c", "d", "e", digest[0]})[:3],
        "score": (int(digest[:4], 16) % 100) / 100.0,
    }
    text = json.dumps(payload, sort_keys=True)
    return {
        "text": text,
        "tokens": _approx_tokens(text),
        "meta": {"digest": digest[:16]},
    }


def mock_code(prompt: str, params: dict) -> dict:
    """A 'code' mock: produces a small Python snippet derived from the prompt.

    Snippets are intentionally trivial (a function stub with the prompt
    baked into the docstring) so the benchmark can grade on syntactic
    validity (compile + import).
    """
    digest = _hash_digest(prompt, "code")
    fn_name = "f_" + digest[:8]
    text = (
        f"# generated by mock_code\n"
        f"def {fn_name}():\n"
        f'    """Auto-generated from prompt: {prompt[:60]!r}"""\n'
        f"    return {digest[:8]}\n"
    )
    return {
        "text": text,
        "tokens": _approx_tokens(text),
        "meta": {"digest": digest[:16], "function_name": fn_name},
    }


# ---------- registry ----------


_REGISTRY: dict[str, ModelInfo] = {}


def register_model(info: ModelInfo) -> None:
    _REGISTRY[info.id] = info


def get_model(model_id: str) -> ModelInfo:
    if model_id not in _REGISTRY:
        raise KeyError(f"unknown model_id: {model_id}")
    return _REGISTRY[model_id]


def list_models() -> list[ModelInfo]:
    return list(_REGISTRY.values())


# Default mock registry
register_model(ModelInfo(
    id="mock-deterministic",
    name="Mock Deterministic",
    description="Stable output derived from prompt hash; same prompt → same output",
    family="mock",
    fn=mock_deterministic,
))
register_model(ModelInfo(
    id="mock-creative",
    name="Mock Creative",
    description="Varying output (5-min salt buckets); useful for diversity benchmarks",
    family="mock",
    fn=mock_creative,
))
register_model(ModelInfo(
    id="mock-structured",
    name="Mock Structured",
    description="JSON-shaped output; useful for JSON-schema conformance benchmarks",
    family="mock",
    fn=mock_structured,
))
register_model(ModelInfo(
    id="mock-code",
    name="Mock Code",
    description="Generates a small Python function derived from the prompt; graded on syntactic validity",
    family="mock",
    fn=mock_code,
))
